title: Reom
author: ComplexAce (Mesh)
additional_authors: Hope (Morphs, Textures)
license: CC-BY

char_obj: cm_reom
basis: Default
default_hair_length: 0.1
default_armature: rigify
default_texture_set: 4K

custom_morph_order: true
recurse_materials: true

materials:
  - Sclera_Cornea
  - Iris
  - Pupil
  - Face
  - Torso
  - Arms
  - Legs
  - Mouth
  - Tongue
  - Gums
  - Teeth

default_assets:
  - Tearline

#underwear:
#  - underpants

armature:
  rigify:
    title: Rigify
    type: rigify
    obj_name: metarig
  arp:
    title: ARP
    type: arp
    obj_name: rig
