title: Reom (CC-BY)
author: ComplexAce (Mesh)
additional_authors: Hope (Morphs, Textures)
license: CC-BY

char_obj: cm_reom
basis: Default
default_hair_length: 0.1
default_armature: rigify
default_texture_set: 4K

hair_library: eyebrows.blend
hair_obj: EyeBrows
hair_shrinkwrap: true
force_hair_scalp: true
hair_shrinkwrap_offset: 0.0002
hairstyles: [Eyebrows001, Eyebrows002, Eyebrows003, Eyebrows004, Eyebrows005, Eyebrows006, Eyebrows007, Eyebrows008, Eyebrows009, Eyebrows010, Eyebrows011, Eyebrows012]

custom_morph_order: true
recurse_materials: true

materials:
  - Sclera_Cornea
  - Iris
  - Pupil
  - Face
  - Torso
  - Arms
  - Legs
  - Mouth
  - Tongue
  - Gums
  - Teeth

default_assets:
  - Tearline

#underwear:
#  - underpants

armature_defaults:
    type: rigify
    file: rigs.blend

armature:
  rigify2:
    title: Rigify
    weights: weights/rigify.npz
    joints: joints/rigify.npz
    obj_name: metarig
    no_legacy: true
  rigify:
    title: Rigify Legacy
    joints: joints/rigify_legacy.npz
    obj_name: metarig_legacy
    tweaks: eyes.yaml
    description: Legacy rig for Blender versions before 3.0
  arp:
    title: ARP
    type: arp
    obj_name: rig
