title: Human female (MB-Lab, AGPL3)
author: Manuel Bastioni
license: AGPL3

default_type: ca01
char_file: char.blend
obj_name: mb_female
material_lib: ../../shared_lib.blend

default_hair_length: 0.3
hair_library: hair.blend
hair_obj: hair
hairstyles:
  - symmetric1
  - back1
  - frontback1

armature:
  -
    type: rigify
    file: ../../shared_lib.blend
    obj_name: metarig
    tweaks: ../../rigify_tweaks.yaml

materials:
  - charmorph_skin
  - charmorph_censor
  - MBlab_eyelash
  - MBlab_pupil
  - MBlab_human_eyes
  - MBlab_cornea
  - charmorph_iris
  - MBLab_tongue
  - MBlab_human_teeth
  - charmorph_nails

types:
  ca01:
    title: Caucasian
    mtl_props:
      skin_color: &col1 [0.896, 0.456, 0.279]
      nails_natural_color: *col1
  an03:
    title: Anime
    mtl_props:
      skin_color: *col1
      nails_natural_color: *col1
  ft01:
    title: Elf
    mtl_props:
      skin_color: *col1
      nails_natural_color: *col1
  la01:
    title: Latin
    mtl_props:
      skin_color: &col2 [0.485, 0.147, 0.080]
      nails_natural_color: *col2
  as01:
    title: Asian
    mtl_props:
      skin_color: *col2
      nails_natural_color: *col2
  af01:
    title: African
    mtl_props:
      skin_color: &col3 [0.07, 0.033, 0.026]
      nails_natural_color: *col3
